### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [gofed/symbols-extractor#143]
This is a mighty fine tool and library. It would be great if it had a bona fide FLOSS license!
Thanks!

**Comment by nim-nim** [comment]
Without a license, the project can’t be used in Fedora

**Comment by ingvagabund** [comment]
Interesting reading: https://www.dwheeler.com/essays/floss-license-slide.html

So what would be the best license in general? In most cases I used GPLv2. Apache 2.0 is used mostly by Go projects. Any thoughts on that?

**Comment by nim-nim** [comment]
If you took some code out of the golang codebase you need to choose a license compatible with this code.

Otherwise any permissive license (BSD 2/3 clause) will be compatible with everything but won't protect your project a lot.

If you go towards copyleft, use GPLv3 as it can use ASL 2.0 code while GPL v2 can't.

**Comment by ingvagabund** [comment]
I just create a symlink to Go's stdlib. Is that considered as "taking some code out of the golang codebase"?

**Comment by nim-nim** [comment]
if it's just a symlink, you're probably not deriving and can license as you wish. (do note that the law cares if stuff is derived or not, not about the technical means used)

**Comment by ingvagabund** [comment]
https://github.com/gofed/symbols-extractor/blob/master/LICENSE
